import type { MigrationReport } from '../types';
import fs from 'fs';
import path from 'path';

export function generateMarkdownReport(report: MigrationReport): string {
  const durationMs =
    new Date(report.endTime).getTime() - new Date(report.startTime).getTime();
  const duration = formatDuration(durationMs);

  const lines: string[] = [
    `# Angular Migration Report`,
    ``,
    `**Project:** \`${report.projectPath}\`  `,
    `**Started:** ${report.startTime}  `,
    `**Completed:** ${report.endTime}  `,
    `**Duration:** ${duration}  `,
    `**Status:** ${report.success ? '✅ Success' : '❌ Failed'}`,
    ``,
    `---`,
    ``,
    `## 1. Audit Results`,
    ``,
    `| Package | Current | Latest | Major Gap | Direct? |`,
    `|---------|---------|--------|-----------|---------|`,
    ...Object.entries(report.audit.packages).map(
      ([name, p]) =>
        `| \`${name}\` | ${p.current} | ${p.latest} | ${p.gap > 0 ? `⚠️ +${p.gap}` : '✅ 0'} | ${p.isDirect ? 'Yes' : 'No'} |`
    ),
    ``,
    `---`,
    ``,
    `## 2. Compatibility Analysis`,
    ``,
    report.compatibility.summary,
    ``,
  ];

  if (report.compatibility.conflicts.length > 0) {
    lines.push(`### Conflicts Detected`, ``);
    for (const c of report.compatibility.conflicts) {
      lines.push(
        `- **${c.package}** conflicts with **${c.conflictsWith}**: ${c.reason}`,
        `  → *Resolution:* ${c.resolution}`,
        ``
      );
    }
  }

  if (report.compatibility.blockers.length > 0) {
    lines.push(`### Blockers`, ``);
    for (const b of report.compatibility.blockers) {
      lines.push(`- 🚫 ${b}`);
    }
    lines.push(``);
  }

  lines.push(`### Safe Upgrade Order`, ``);
  for (const step of report.compatibility.upgradeOrder) {
    const via =
      step.intermediateVersions.length > 0
        ? ` *(via ${step.intermediateVersions.join(' → ')})*`
        : '';
    lines.push(`${step.order}. **${step.package}** ${step.fromVersion} → ${step.toVersion}${via}`);
    for (const note of step.notes) {
      lines.push(`   - ${note}`);
    }
  }

  lines.push(
    ``,
    `---`,
    ``,
    `## 3. Migration Plan`,
    ``,
    `**Complexity:** ${report.plan.estimatedComplexity.toUpperCase()}  `,
    `**Total Steps:** ${report.plan.totalSteps}`,
    ``
  );

  for (const step of report.plan.steps) {
    const manual = step.requiresManualReview ? ' ⚠️ *Manual review required*' : '';
    lines.push(`### Step ${step.order}: ${step.description}${manual}`, ``);
    lines.push(`**Type:** \`${step.type}\`  `);
    if (step.migrationRule) lines.push(`**Rule:** ${step.migrationRule}  `);
    if (step.notes) lines.push(`**Notes:** ${step.notes}  `);
    lines.push(``);
    if (step.commands && step.commands.length > 0) {
      lines.push('```bash', ...step.commands, '```', ``);
    }
  }

  lines.push(`---`, ``, `## 4. Execution Log`, ``);

  for (const entry of report.executionLog) {
    const icon = entry.result === 'success' ? '✅' : entry.result === 'skipped' ? '⏭️' : '❌';
    lines.push(`- ${icon} **[${entry.stepId}]** ${entry.action}  `);
    lines.push(`  ${entry.details}`);
  }

  lines.push(``, `---`, ``);

  if (report.filesModified.length > 0) {
    lines.push(`## 5. Files Modified`, ``);
    for (const f of report.filesModified) {
      lines.push(`- \`${f}\``);
    }
    lines.push(``);
  }

  if (report.manualStepsRequired.length > 0) {
    lines.push(
      `## 6. Manual Steps Required`,
      ``,
      `> These steps could not be automated and require developer attention:`,
      ``
    );
    for (const s of report.manualStepsRequired) {
      lines.push(`- [ ] ${s}`);
    }
    lines.push(``);
  }

  if (report.errors.length > 0) {
    lines.push(`## 7. Errors`, ``);
    for (const e of report.errors) {
      lines.push(`- ❌ ${e}`);
    }
    lines.push(``);
  }

  lines.push(`---`, ``, `*Generated by angular-migration-agent*`);

  return lines.join('\n');
}

export function writeReport(report: MigrationReport, outputPath?: string): string {
  const markdown = generateMarkdownReport(report);
  const dest = outputPath ?? path.join(report.projectPath, 'migration-report.md');
  fs.writeFileSync(dest, markdown, 'utf-8');
  return dest;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const mins = Math.floor(ms / 60_000);
  const secs = Math.floor((ms % 60_000) / 1000);
  return `${mins}m ${secs}s`;
}
